version: '3.8'

services:
  osre-owner:
    image: osre-owner
    build:
      context: ..
      dockerfile: docker/Dockerfile.owner
    networks:
      osre_network:
        ipv4_address: 172.28.0.2
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    depends_on:
      - osre-device

  osre-device:
    image: osre-device
    build:
      context: ..
      dockerfile: docker/Dockerfile.device
    networks:
      osre_network:
        ipv4_address: 172.28.0.3
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    depends_on:
      - osre-proxy

  osre-proxy:
    image: osre-proxy
    build:
      context: ..
      dockerfile: docker/Dockerfile.proxy
    networks:
      osre_network:
        ipv4_address: 172.28.0.4
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    depends_on:
      - osre-holder_1
      - osre-holder_2
      - osre-holder_3
      - osre-holder_4
      - osre-holder_5
  
  osre-holder_1:
    image: osre-holder
    container_name: osre-holder_1
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    networks:
      osre_network:
        ipv4_address: 172.28.0.11
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    command: ["172.28.0.11"]

  
  osre-holder_2:
    image: osre-holder
    container_name: osre-holder_2
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    networks:
      osre_network:
        ipv4_address: 172.28.0.12
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    command: ["172.28.0.12"]

  
  osre-holder_3:
    image: osre-holder
    container_name: osre-holder_3
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    networks:
      osre_network:
        ipv4_address: 172.28.0.13
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    command: ["172.28.0.13"]

  
  osre-holder_4:
    image: osre-holder
    container_name: osre-holder_4
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    networks:
      osre_network:
        ipv4_address: 172.28.0.14
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    command: ["172.28.0.14"]

  
  osre-holder_5:
    image: osre-holder
    container_name: osre-holder_5
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    networks:
      osre_network:
        ipv4_address: 172.28.0.15
    ports:
      - "55555"
    volumes:
      - log-data:/logs
    command: ["172.28.0.15"]

networks:
  osre_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
    #name: osre_network
    #external: true
    
volumes:
  log-data:
    external: true
